name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * 1"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:    
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: jeffersonfed/jeffersonfed
          # content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: => 
          CODE_LANG: txt
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.org
          AUTHOR_NAME: Jefferson
#       - uses: actions/checkout@master
#       - name: Update gist
#         uses: matchai/waka-box@master
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           GIST_ID: 
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        
